### ISSUE TITLE
Could not find com.facebook.react:react-native-webrtc:1.69.2-jitsi-2062090 dependency 

### ISSUE THREAD

**Issue by mariolon** [matrix-org/matrix-android-sdk#569]
Hello, 

I am facing an issue regarding `com.facebook.react:react-native-webrtc:1.69.2-jitsi-2062090` (check snippet below). Seems like it is removed from jCenter so I am unable to build application with Matrix SDK since it cannot fetch the dependency anymore. This is a big issue at the moment since basically I am stuck with development and CI also won't create builds and migration to Matrix2 is currently difficult to make since there is no guide or similarities between Matrix1 and Matrix2. Is there any other place where Matrix SDK and all of its dependencies are hosted and can be used even though it is deprecated? Or is there any other solution besides switching to Matrix2? 

Any help would be appreciated!
Thank you

Mario 

```
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-native-webrtc:1.69.2-jitsi-2062090.
     Searched in the following locations:
       - https://github.com/vector-im/jitsi_libre_maven/raw/master/releases/com/facebook/react/react-native-webrtc/1.69.2-jitsi-2062090/react-native-webrtc-1.69.2-jitsi-2062090.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native-webrtc/1.69.2-jitsi-2062090/react-native-webrtc-1.69.2-jitsi-2062090.pom
       - https://jcenter.bintray.com/com/facebook/react/react-native-webrtc/1.69.2-jitsi-2062090/react-native-webrtc-1.69.2-jitsi-2062090.pom
       - https://repo.maven.apache.org/maven2/com/facebook/react/react-native-webrtc/1.69.2-jitsi-2062090/react-native-webrtc-1.69.2-jitsi-2062090.pom
     Required by:
         project :app > com.github.matrix-org:matrix-android-sdk:v0.9.32 > com.github.matrix-org.matrix-android-sdk:matrix-sdk:v0.9.32
```

**Comment by bmarty** [comment]
It was probably a temporary issue. You closed it because it's fixed now?

**Comment by mariolon** [comment]
> It was probably a temporary issue. You closed it because it's fixed now?

@bmarty 

The issue was that the MatrixSDK used old path to jitsi on jCenter which no longer exists. So the solution was to exclude the path from the library and use jitsi that is hosted on `https://github.com/vector-im/jitsi_libre_maven`.

Specifically, 
```
implementation ('com.github.matrix-org:matrix-android-sdk:v0.9.32') {
     exclude group: 'com.facebook.react', module: 'react-native-webrtc'
}
```

```
 maven {
     url "https://github.com/vector-im/jitsi_libre_maven/raw/master/releases"
  }
```

Luckily that repo still exists! :) 

Thanks for the help anyway! :)
